#config_version=6

# Attract mode that starts when the machine boots up, stops
# whenever a game is started, and re-starts after the game ends.

mode:
  code: attract.Attract

mode_settings:
  extra_bosses_light_show_settings:
    lerp_interval: 31

show_player:

  mode_attract_started: attract_shows_playlist

    # attract_extra_bosses_light_show:
    #   speed: 8
    #   events_when_stopped: attract_extra_bosses_light_show_stopped
    #   events_when_looped: attract_extra_bosses_light_show_looped

    # attract_wipe_ul_to_lr_light_show:
    #   speed: 20
    #   events_when_stopped: attract_wipe_ul_to_lr_light_show_stopped
    #   events_when_looped: attract_wipe_ul_to_lr_light_show_looped

    # attract_wipe_r_to_l_light_show:
    #   speed: 20
    #   events_when_stopped: attract_wipe_r_to_l_light_show_stopped
    #   events_when_looped: attract_wipe_r_to_l_light_show_looped

    # attract_grid_light_show:
    #   speed: 6
    # attract_host_panel_light_show:
    #   speed: 6
    # attract_playfield_multiplier_light_show:
    #   speed: 6
    # attract_scoop_bb_mystery_light_show.1:
    #   speed: 6
    # attract_scoop_bb_mystery_light_show.2:
    #   speed: 6

