#config_version=6

# Attract mode that starts when the machine boots up, stops
# whenever a game is started, and re-starts after the game ends.

mode:
  code: attract.Attract

show_player:
  mode_attract_started:

    attract_extra_bosses_light_show:
      speed: 8
      events_when_stopped: attract_extra_bosses_light_show_stopped
      events_when_looped: attract_extra_bosses_light_show_looped

    # attract_grid_light_show:
    #   speed: 4

