#config_version=6

# Attract mode that starts when the machine boots up, stops
# whenever a game is started, and re-starts after the game ends.

mode:
  code: attract.Attract

# slide_player:
#   mode_attract_started: attract

# timers:
#   ndx1111:
#     start_value: 1
#     end_value: 10
#     control_events:
#       - action: start
#         event: mode_attract_started

show_player:
  mode_attract_started:
    attract_light_show:
      speed: 8
      events_when_looped: attract_light_show_looped
      events_when_stopped: attract_light_show_stopped
      # loops: -1
      # events_when_completed:
      #   - 
      # show_tokens:
      #   this_color: "FF0000"

#   # timer_ndx1111_tick: this event handler is in attract.py
#     attract_light_show:
#       action: advance

# event_player:
#   timer_ndx1111_tick: new_event1

# variable_player:
#   new_event1:
#     next_color:
#       action: set_machine
#       int: machine.next_color + 1
