#config_version=6

hardware:
  platform: spike

spike:
  
  # port identified in Windows device manager after installing FTDI driver and
  # plugging in USB null modem cable
  port: COM4

  baud: 115200
  flow_control: false
  debug: true
  runtime_baud: 115200
  nodes: 0, 1, 8, 9