#config_version=6

lights:
  l_1_coin_enable:
    number:
  l_2_start_button:
    number:
  l_3_tournament_start_button:
    number:
  l_4_action_button:
    number:

  l_11_left_out_lane:
    number:
  l_12_left_return_lane:
    number:
  l_13_right_return_lane:
    number:
  l_14_right_out_lane:
    number:
  l_15_shoot_again:
    number:

  l_18_riot_matrix_r1c1:
    number:
  l_22_riot_matrix_r2c1:
    number:
  l_26_riot_matrix_r3c1:
    number:
  l_30_riot_matrix_r4c1:
    number:

  l_34_agony_matrix_r1c2:
    number:
  l_38_agony_matrix_r2c2:
    number:
  l_42_agony_matrix_r3c2:
    number:
  l_46_agony_matrix_r4c2:
    number:

  l_50_phage_matrix_r1c3:
    number:
  l_54_phage_matrix_r2c3:
    number:
  l_58_phage_matrix_r3c3:
    number:
  l_62_phage_matrix_r4c3:
    number:

  l_66_lasher_matrix_r1c4:
    number:
  l_70_lasher_matrix_r2c4:
    number:
  l_74_lasher_matrix_r3c4:
    number:
  l_78_lasher_matrix_r4c4:
    number:

  l_83_team_up_1:
    number:
  l_84_team_up_2:
    number:
  l_85_team_up_3:
    number:

##############################################################
###
### Added to MPF Monitor playfield up through this marker
###
##############################################################

  l_88_venomized_1:
    number:
  l_89_venomized_2:
    number:
  l_90_venomized_3:
    number:

  l_91_knull:
    number:
  l_94_grendel:
    number:

  1_99_1x:
    number:
  1_100_2x:
    number:
  1_101_4x:
    number:

  1_104_left_target:
    number:
  1_105_right_target:
    number:

  1_108_left_orbit:
    number:
  1_111_left_orbit_web:
    number:

  1_114_left_ramp:
    number:
  1_117_left_ramp_web:
    number:
  1_118_left_ramp_lock:
    number:
  1_121_change_host:
    number:

  1_124_carnage_1:
    number:
  1_127_carnage_2:
    number:
  1_128_carnage_3:
    number:
  1_129_carnage_inf:
    number:

  1_132_center_ramp:
    number:
  1_135_center_ramp_web:
    number:
  1_136_center_ramp_lock:
    number:
  1_139_start:
    number:

  1_144_bell_tower:
    number:
  1_147_bell_tower_inf:
    number:

  1_150_left_loop:
    number:
  1_153_left_loop_web:
    number:
  1_154_left_loop_lock:
    number:

  1_159_mini_target_left:
    number:
  1_160_mini_target_right:
    number:

  1_163_scoop:
    number:
  1_166_scoop_web:
    number:
  1_167_scoop_lock:
    number:
  1_170_mystery:
    number:
  1_171_extra_ball:
    number:

  1_174_right_loop:
    number:
  1_177_right_loop_web:
    number:
  1_178_right_loop_lock:
    number:

  1_183_right_orbit:
    number:
  1_186_right_orbit_web:
    number:
  1_187_right_orbit_lock:
    number:

  192_down_3_bank_left:
    number:
  193_down_3_bank_center:
    number:
  194_down_3_bank_right:
    number:
  195_down_3_bank_2nd_left:
    number:
  196_down_3_bank_2nd_center:
    number:
  197_down_3_bank_2nd_center:
    number:
  198_rampage:
    number:

  201_top_lane_left_2x:
    number:
  202_top_lane_right_2x:
    number:
  203_ravencroft_1_2x:
    number:
  204_ravencroft_2:
    number:

  207_host_bb_1:
    number:
  208_host_bb_2:
    number:
  209_host_bb_3:
    number:
  210_host_bb_4:
    number:
  211_host_bb_5:
    number:
  212_host_bb_6:
    number:
  213_host_bb_7:
    number:

  216_left_bb_lock_1:
    number:
  217_left_bb_lock_2:
    number:
  218_left_bb_lock_3:
    number:

  221_right_bb_lock_1:
    number:
  222_right_bb_lock_2:
    number:
  223_right_bb_lock_3:
    number:

  226_scoop_bb_mystery_1:
    number:
  227_scoop_bb_mystery_2:
    number:
  228_scoop_bb_mystery_3:
    number:
  229_scoop_bb_mystery_4:
    number:
  230_scoop_bb_mystery_5:
    number:
  231_scoop_bb_battle_1:
    number:
  232_scoop_bb_battle_2:
    number:
  233_scoop_bb_battle_3:
    number:

  245_coin_door_gi:
    number:
  246_left_gi_1_x6:
    number:
  247_left_gi_red_x7:
    number:
  248_left_gi_2_x5:
    number:
  249_right_gi_1_x6:
    number:
  250_right_gi_red_x6:
    number:
  251_right_gi_2_backpanel_x3:
    number:

  255_lower_left_flash:
    number:
  256_lower_right_flash:
    number:

  258_left_pop_flash:
    number:
  259_right_pop_flash:
    number:
  260_up_left_flash:
    number:
  261_up_right_flash:
    number:
  262_ravencroft_flash_wht:
    number:
  263_ravencroft_flash_red:
    number:
