#config_version=6

# there are many more playfield_active switches, confirm them all when I'm with the machine
switches:
  s_1_left_outlane:
    number: 8-17 # 8-SW-17
  s_2_left_return_lane:
    number: 8-18 # 8-SW-18
    tags: playfield_active # physically confirm when at machine
  s_5_right_return_lane:
    number: 8-19 # 8-SW-19
    tags: playfield_active # physically confirm when at machine
  s_6_right_outlane:
    number: 8-20 # 8-SW-20
  s_7_left_slingshot:
    number: 8-30 # 8-SW-30
    tags: playfield_active # physically confirm when at machine
  s_8_right_slingshot:
    number: 8-29 # 8-SW-29
    tags: playfield_active # physically confirm when at machine
  s_9_left_flipper_button:
    number: 8-25 # 8-SW-25
    tags: left_flipper
  s_10_right_flipper_button:
    number: 8-24 # 8-SW-24
    tags: right_flipper
  s_11_left_flipper_eos:
    number: 8-16 # 8-SW-16
  s_12_right_flipper_eos:
    number: 8-31 # 8-SW-31
  s_15_trough_6:
    number: 8-32 # 8-SW-32
  s_16_trough_5:
    number: 8-33 # 8-SW-33
  s_17_trough_4:
    number: 8-34 # 8-SW-34
  s_18_trough_3:
    number: 8-35 # 8-SW-35
  s_19_trough_2:
    number: 8-36 # 8-SW-36
  s_20_trough_1:
    number: 8-37 # 8-SW-37
  s_21_trough_jam:
    number: 8-38 # 8-SW-38
  s_22_shooter_lane:
    number: 8-28 # 8-SW-28
  s_25_upper_shooter_lane:
    number: 8-21 # 8-SW-21
  s_28_left_target:
    number: 8-8 # 8-SW-8
    tags: playfield_active # physically confirm when at machine
  s_32_left_lock_1_opto:
    number: 8-11 # 8-SW-11
  s_33_left_lock_2_opto:
    number: 8-12 # 8-SW-12
  s_34_left_lock_3_opto:
    number: 8-13 # 8-SW-13
  s_39_right_target:
    number: 8-22 # 8-SW-22
    tags: playfield_active # physically confirm when at machine
  s_42_right_lock_1_opto:
    number: 8-3 # 8-SW-3
  s_43_right_lock_2_opto:
    number: 8-4 # 8-SW-4
  s_44_right_lock_3_opto:
    number: 8-5 # 8-SW-5
  s_47_down_3_bank-left:
    number: 8-0 # 8-SW-0
    tags: playfield_active # physically confirm when at machine
  s_48_down_3_bank-center:
    number: 8-1 # 8-SW-1
    tags: playfield_active # physically confirm when at machine
  s_49_down_3_bank-right:
    number: 8-2 # 8-SW-2
    tags: playfield_active # physically confirm when at machine
  s_51_left_orbit:
    number: 9-27 # 9-SW-27
    tags: playfield_active # physically confirm when at machine
  s_52_top_post_opto:
    number: 9-17 # 9-SW-17
  s_53_top_lane-left:
    number: 9-30 # 9-SW-30
    tags: playfield_active # physically confirm when at machine
  s_54_top_lane-right:
    number: 9-31 # 9-SW-31
    tags: playfield_active # physically confirm when at machine
  s_55_right_orbit:
    number: 9-10 # 9-SW-10
    tags: playfield_active # physically confirm when at machine
  s_57_left_pop_bumper:
    number: 9-28 # 9-SW-28
    tags: playfield_active # physically confirm when at machine
  s_58_right_pop_bumper:
    number: 9-29 # 9-SW-29
    tags: playfield_active # physically confirm when at machine
  s_59_10_pt_sw:
    number: 9-24 # 9-SW-24
  s_60_left_loop_enter_opto:
    number: 9-14 # 9-SW-14
    tags: playfield_active # physically confirm when at machine
  s_62_bell_tower_target:
    number: 9-16 # 9-SW-16
    tags: playfield_active # physically confirm when at machine
  s_63_left_mini_target:
    number: 9-11 # 9-SW-11
    tags: playfield_active # physically confirm when at machine
  s_64_right_mini_target:
    number: 9-12 # 9-SW-12
    tags: playfield_active # physically confirm when at machine
  s_65_180_scoop_made:
    number: 9-8 # 9-SW-8
  s_66_r_ramp_made_opto:
    number: 9-9 # 9-SW-9
  s_68_left_ramp_made:
    number: 9-25 # 9-SW-25
  s_70_center_ramp_made:
    number: 9-19 # 9-SW-19
  s_72_carnage_ball_home:
    number: 9-0 # 9-SW-0
  s_73_carnage_50_percent_opto:
    number: 9-1 # 9-SW-1
  s_74_carnage_75_percent_opto:
    number: 9-2 # 9-SW-2
  s_75_carnage_away:
    number: 9-3 # 9-SW-3
  s_76_scoop_made_opto:
    number: 9-4 # 9-SW-4
  s_79_vuk_opto:
    number: 9-5 # 9-SW-5
  s_80_loop_hole_entrance_opto:
    number: 9-6 # 9-SW-6
  s_81_subway_left_opto:
    number: 9-7 # 9-SW-7
  s_84_scoop_motor_1:
    number: 9-21 # 9-SW-21
  s_85_scoop_motor_2:
    number: 9-22 # 9-SW-22
  s_87_scoop_motor_3:
    number: 9-23 # 9-SW-23
  s_90_right_loop_entrance:
    number: 9-15 # 9-SW-15
    tags: playfield_active # physically confirm when at machine
  s_100_lockdown_button:
    number: 1-2 # 1-SW-2
  s_103_start_button:
    number: 1-11 # 1-SW-11
    tags: start
  s_104_tournament_start_button:
    number: 1-12 # 1-SW-12
  s_106_left_coin:
    number: 1-16 # 1-SW-16
  s_107_right_coin:
    number: 1-18 # 1-SW-18
  s_108_center_coin:
    number: 1-17 # 1-SW-17
  s_109_fourth_coin:
    number: 1-19 # 1-SW-19
  s_110_fifth_coin:
    number: 1-20 # 1-SW-20
  s_111_tilt_pendulum:
    number: 1-14 # 1-SW-14
    tags: tilt_warning
  s_112_sixth_coin:
    number: 1-21 # 1-SW-21
  s_113_ticket_notch:
    number: 1-8 # 1-SW-8
  s_114_slam_tilt:
    number: 1-22 # 1-SW-22
    tags: slam_tilt
  s_C9_service_select:
    number: 0-8 # 0-SW-8
    tags: service_enter
  s_C10_service_plus:
    number: 0-9 # 0-SW-9
    tags: service_up
  s_C11_service_minus:
    number: 0-10 # 0-SW-10
    tags: service_down
  s_C12_service_back:
    number: 0-11 # 0-SW-11
    tags: service_esc
  s_C17_Headphone_Detect_Coin_Door:
    number: 0-16 # 0-SW-16
  s_C18_headphone_kit_cable_detect:
    number: 0-17 # 0-SW-17
  s_C19_volume_encoder_1:
    number: 0-18 # 0-SW-18
  s_C20_volume_encoder_2:
    number: 0-19 # 0-SW-19
  s_C24_coin_door_interlock:
    number: 0-23 # 0-SW-23
